manipulator: 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: front_right_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.01} 

  right_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: front_left_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  rear_wheel_controller: 
    type: velocity_controllers/JointVelocityController
    joint: rear_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 


 